In [71]:
import numpy as np # pip install numpy

In [72]:
arr = np.arange(2, 25)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [73]:
arr * 2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [74]:
arr**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [75]:
arr + 10

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34])

In [76]:
arr - 10

array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14])

In [77]:
arr + arr

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [78]:
arr * arr

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [79]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [80]:
2/arr

array([1.        , 0.66666667, 0.5       , 0.4       , 0.33333333,
       0.28571429, 0.25      , 0.22222222, 0.2       , 0.18181818,
       0.16666667, 0.15384615, 0.14285714, 0.13333333, 0.125     ,
       0.11764706, 0.11111111, 0.10526316, 0.1       , 0.0952381 ,
       0.09090909, 0.08695652, 0.08333333])

In [81]:
np.sqrt(arr)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
       4.69041576, 4.79583152, 4.89897949])

In [82]:
np.sin(arr)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
       -0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
       -0.96139749, -0.75098725,  0.14987721,  0.91294525,  0.83665564,
       -0.00885131, -0.8462204 , -0.90557836])

In [83]:
arr.sum()

np.int64(299)

In [84]:
arr.mean()

np.float64(13.0)