In [1]:
import numpy as np # pip install numpy

In [2]:
my_list = [45, 78, 779]
my_list

[45, 78, 779]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)


array([ 45,  78, 779])

In [5]:
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[ 451,  13, 79], [ 5,  7, 9], [ 45,  178, 779]]
my_matrix

[[451, 13, 79], [5, 7, 9], [45, 178, 779]]

In [7]:
np.array(my_matrix)

array([[451,  13,  79],
       [  5,   7,   9],
       [ 45, 178, 779]])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.random.rand(10)

array([0.36834045, 0.55299131, 0.87508904, 0.93785293, 0.51977526,
       0.24163677, 0.80873924, 0.08620779, 0.41083708, 0.68614122])

In [21]:
np.random.rand(2, 2)

array([[0.25455014, 0.419325  ],
       [0.89708464, 0.95888041]])

In [23]:
# normal distribution
np.random.randn(5)

array([-1.24010566,  0.90291406, -0.41508049,  0.55493258,  0.40136045])

In [24]:
np.random.randn(2, 2)

array([[ 0.0131318 , -0.775485  ],
       [ 1.10035427,  1.29274764]])

In [26]:
np.random.normal(loc=70, scale=10, size=10)

array([64.23603435, 80.53160422, 73.19083917, 69.32938035, 64.74381171,
       79.27073672, 66.65151708, 63.94502992, 69.43654424, 71.53447362])

In [27]:
np.random.randn(10)*10+70

array([76.58010954, 56.21027502, 73.27160253, 72.44174091, 71.64585913,
       75.59738956, 70.21177334, 66.23390982, 87.14575446, 70.70452603])

In [29]:
np.random.randint(10, 99)

75

In [30]:
np.random.randint(10, 99, 20)

array([47, 95, 11, 41, 65, 97, 97, 54, 16, 41, 65, 21, 29, 16, 12, 72, 81,
       62, 92, 94])

In [31]:
np.random.randint(10, 99, (5, 5))

array([[24, 59, 88, 66, 57],
       [30, 78, 95, 14, 59],
       [73, 43, 38, 68, 34],
       [36, 71, 36, 14, 23],
       [48, 46, 35, 68, 39]])

In [38]:
np.random.seed(42)
np.random.randint(10, 99, 10)

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97])

In [39]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = arr.reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
rand_arr = np.random.randint(0, 1000, 10)
rand_arr

array([372,  99, 871, 663, 130, 661, 308, 769, 343, 491])

In [43]:
rand_arr.max()

np.int64(871)

In [44]:
rand_arr.min()

np.int64(99)

In [45]:
rand_arr.argmax()

np.int64(2)

In [46]:
rand_arr.argmin()

np.int64(1)

In [47]:
rand_arr.dtype

dtype('int64')