In [1]:
import numpy as np # pip install numpy

In [49]:
arr = np.arange(2, 25)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [50]:
arr[6]

np.int64(8)

In [51]:
arr[0:6]

array([2, 3, 4, 5, 6, 7])

In [52]:
arr[::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [53]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2])

In [54]:
sliced_arr = arr[:5]
sliced_arr

array([2, 3, 4, 5, 6])

In [55]:
sliced_arr[:] = 13
sliced_arr

array([13, 13, 13, 13, 13])

In [56]:
arr

array([13, 13, 13, 13, 13,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [57]:
sliced_arr[0] = 356

In [58]:
arr

array([356,  13,  13,  13,  13,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [59]:
arr_2d = np.random.randint(10, 100, (5, 5))
arr_2d

array([[39, 47, 11, 73, 69],
       [30, 42, 85, 67, 31],
       [98, 58, 68, 51, 69],
       [89, 24, 71, 71, 56],
       [71, 60, 64, 73, 12]])

In [61]:
arr_2d[2][4]

np.int64(69)

In [62]:
arr_2d[2, 4]

np.int64(69)

In [64]:
arr_2d[:3, 1:]

array([[47, 11, 73, 69],
       [42, 85, 67, 31],
       [58, 68, 51, 69]])

In [66]:
arr = np.arange(2, 9)
arr

array([2, 3, 4, 5, 6, 7, 8])

In [67]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False,  True,  True,  True])

In [68]:
arr[bool_arr]

array([6, 7, 8])

In [69]:
arr[arr%3==0]

array([3, 6])